//created on: 2017-04-02
package com.sample

import noob.pwr.Warehouse;
import noob.pwr.Status;

rule "No Trucks"

    when
        w : Warehouse( numberOfTrucks() == 0, ShouldCheck())
    then
        w.setStatus(Status.Invalid);
		System.out.println(drools.getRule().getName() + ": Warehouse status is " + w.status);
		update(w);

end

rule "No Items"
   when
        w : Warehouse( numberOfProducts() == 0, ShouldCheck())
    then
        w.setStatus(Status.Invalid);
		System.out.println(drools.getRule().getName() + ": Warehouse status is " + w.status);
		update(w);

end
